# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 771110a277db362af100c88f63e6984c0906b9ff9903be84fd238e565fb0d4923660d908932b144f38b82f4458f599811a4df2ea1b5a80f262b236285df9fe7f

test:
  secret_key_base: 4ac4cddbca0ca19b478e72fe9f159dd1d8eebf3b491fff6c527bbd3bb2724a859eb688c0044270e243bcc961ad353ca2b4f33c3c91671cf39e7c3d51df14f272

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
